import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  WIKI_COPYRIGHT_HOLDER,
  WIKI_COPYRIGHT_HOLDER_URL,
  WIKI_NAME,
} from "@/lib/config";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: WIKI_NAME,
  description: `Generated by ${WIKI_NAME}`,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen p-4 mx-auto max-w-2xl">
          <header className="flex justify-between">
            <p className="text-xl font-bold">
              <Link href={"/"}>{WIKI_NAME}</Link>
            </p>
            <Link href={"/signin"}>Sign In</Link>
          </header>
          {children}
          <footer className="mt-4">
            <p className="text-sm text-gray-500">
              &copy; {new Date().getFullYear()}{" "}
              <a
                href={WIKI_COPYRIGHT_HOLDER_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="hover:underline"
              >
                {WIKI_COPYRIGHT_HOLDER}
              </a>
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
